-- Alina Baby, Nithila Annadurai, Peter Alonzo (Group 1: Tech Catalyst DE 2024)
-- SQL Queries for Data Validation/Pattern Detection

-- General Select Statements for Data Validation
SELECT * FROM TAXI_ZONE_TBL;
SELECT * FROM LICENSE_TBL;
SELECT * FROM TAXI_TBL LIMIT 5;
SELECT * FROM HIGH_VOLUME_TBL LIMIT 5;

-- View of Borough PU/DO for every taxi trip
SELECT PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY, PU_LOCATIONID, TZ.BOROUGH AS PU_BOROUGH, DO_LOCATIONID, TZ2.BOROUGH AS DO_BOROUGH
FROM TAXI_TBL AS T JOIN TAXI_ZONE_TBL AS TZ ON T.PU_LOCATIONID = TZ.LOCATION_ID
JOIN TAXI_ZONE_TBL AS TZ2 ON T.DO_LOCATIONID = TZ2.LOCATION_ID
LIMIT 10;

-- View of Borough PU/DO for every hvfhv trip
SELECT PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY, PU_LOCATIONID, TZ.BOROUGH AS PU_BOROUGH, DO_LOCATIONID, TZ2.BOROUGH AS DO_BOROUGH
FROM HIGH_VOLUME_TBL AS H JOIN TAXI_ZONE_TBL AS TZ ON H.PU_LOCATIONID = TZ.LOCATION_ID
JOIN TAXI_ZONE_TBL AS TZ2 ON H.DO_LOCATIONID = TZ2.LOCATION_ID
LIMIT 10;

-- View of company name for hvfhv data
SELECT H.LICENSE_NUM, L.COMPANY_NAME AS COMPANY_NAME, PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY
FROM HIGH_VOLUME_TBL AS H JOIN LICENSE_TBL AS L ON H.LICENSE_NUM = L.LICENSE_NUM
LIMIT 10;

-- View of all tables joined to hvfhv data
SELECT H.LICENSE_NUM, L.COMPANY_NAME AS COMPANY_NAME, PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY, PU_LOCATIONID, TZ.BOROUGH AS PU_BOROUGH, DO_LOCATIONID, TZ2.BOROUGH AS DO_BOROUGH
FROM HIGH_VOLUME_TBL AS H JOIN TAXI_ZONE_TBL AS TZ ON H.PU_LOCATIONID = TZ.LOCATION_ID
JOIN TAXI_ZONE_TBL AS TZ2 ON H.DO_LOCATIONID = TZ2.LOCATION_ID
JOIN LICENSE_TBL AS L ON H.LICENSE_NUM = L.LICENSE_NUM
LIMIT 10;

-- Checking for Outliers
SELECT * FROM TAXI_TBL--HIGH_VOLUME_TBL
WHERE YEAR NOT IN (2023, 2024);

SELECT PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY, PU_LOCATIONID, TZ.BOROUGH AS PU_BOROUGH, DO_LOCATIONID, TZ2.BOROUGH AS DO_BOROUGH
FROM HIGH_VOLUME_TBL AS H JOIN TAXI_ZONE_TBL AS TZ ON H.PU_LOCATIONID = TZ.LOCATION_ID
JOIN TAXI_ZONE_TBL AS TZ2 ON H.DO_LOCATIONID = TZ2.LOCATION_ID
WHERE PU_BOROUGH NOT IN ('Staten Island', 'Bronx', 'Manhattan', 'Queens', 'Brooklyn', 'EWR') OR DO_BOROUGH NOT IN ('Staten Island', 'Bronx', 'Manhattan', 'Queens', 'Brooklyn', 'EWR');

SELECT TRIP_DURATION, TRIP_DISTANCE, TOTAL_AMOUNT, TOTAL_AMOUNT / TRIP_DURATION AS "Cost Per Minute", TOTAL_AMOUNT / TRIP_DISTANCE AS "Cost Per Mile"
FROM TAXI_TBL
ORDER BY "Cost Per Minute" DESC, "Cost Per Mile" DESC
LIMIT 100;

SELECT TRIP_DURATION FROM TAXI_TBL
ORDER BY TRIP_DURATION DESC
LIMIT 100;

-- Data Transformations (to be added to Databricks)
DELETE FROM HIGH_VOLUME_TBL--TAXI_TBL
WHERE TRIP_DISTANCE < 0.1;

DELETE FROM HIGH_VOLUME_TBL--TAXI_TBL
WHERE TRIP_DURATION <= 0;

DELETE FROM HIGH_VOLUME_TBL--TAXI_TBL (6 rows for Uber, 18007 for Taxi)
WHERE TRIP_DURATION > 720; -- 12 hours

DELETE FROM HIGH_VOLUME_TBL --TAXI_TBL
WHERE (TOTAL_AMOUNT / TRIP_DISTANCE) > 500;

DELETE FROM HIGH_VOLUME_TBL --TAXI_TBL
WHERE DO_LOCATIONID IN (264, 265);

DELETE FROM HIGH_VOLUME_TBL -- 356 rows from HVFHV
WHERE DRIVER_PAY < 0;

-- Testing
SELECT * FROM TAXI_TBL
LIMIT 100;

SELECT * FROM HIGH_VOLUME_TBL
LIMIT 100;
