-- Alina Baby, Nithila Annadurai, Peter Alonzo (Group 1: Tech Catalyst DE 2024)
-- SQL Queries for Data Validation/Pattern Detection

-- General Select Statements for Data Validation
SELECT * FROM TAXI_ZONE_TBL;
SELECT * FROM LICENSE_TBL;
SELECT * FROM TAXI_TBL LIMIT 5;
SELECT * FROM HIGH_VOLUME_TBL LIMIT 5;

-- View of Borough PU/DO for every taxi trip
SELECT PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY, PU_LOCATIONID, TZ.BOROUGH AS PU_BOROUGH, DO_LOCATIONID, TZ2.BOROUGH AS DO_BOROUGH
FROM TAXI_TBL AS T JOIN TAXI_ZONE_TBL AS TZ ON T.PU_LOCATIONID = TZ.LOCATION_ID
JOIN TAXI_ZONE_TBL AS TZ2 ON T.DO_LOCATIONID = TZ2.LOCATION_ID
LIMIT 10;

-- View of Borough PU/DO for every hvfhv trip
SELECT PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY, PU_LOCATIONID, TZ.BOROUGH AS PU_BOROUGH, DO_LOCATIONID, TZ2.BOROUGH AS DO_BOROUGH
FROM HIGH_VOLUME_TBL AS H JOIN TAXI_ZONE_TBL AS TZ ON H.PU_LOCATIONID = TZ.LOCATION_ID
JOIN TAXI_ZONE_TBL AS TZ2 ON H.DO_LOCATIONID = TZ2.LOCATION_ID
LIMIT 10;

-- View of company name for hvfhv data
SELECT H.LICENSE_NUM, L.COMPANY_NAME AS COMPANY_NAME, PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY
FROM HIGH_VOLUME_TBL AS H JOIN LICENSE_TBL AS L ON H.LICENSE_NUM = L.LICENSE_NUM
LIMIT 10;
