-- Alina Baby, Nithila Annadurai, Peter Alonzo (Group 1: Tech Catalyst DE 2024)
-- Architecture Creation Statements
-- Created personal schema for capstone project
CREATE SCHEMA GROUP_1; 

-- Created external stage to access transformed bucket in S3
CREATE OR REPLACE STAGE CAPSTONE_DE.GROUP_1.TRANSFORMED_STAGE 
    STORAGE_INTEGRATION = s3_int
    URL='s3://capstone-techcatalyst-transformed/group1';

-- Created personal file format to read parquet files in S3
CREATE OR REPLACE FILE FORMAT group1_parquet_format
TYPE = 'PARQUET';

-- Table Creation Statements
-- Create Statement for HVFHV data (HIGH_VOLUME_TBL)
CREATE OR REPLACE TRANSIENT TABLE CAPSTONE_DE.GROUP_1.HIGH_VOLUME_TBL (
    LICENSE_NUM STRING,
    PU_DATETIME DATETIME,
    DO_DATETIME DATETIME,
    REQUEST_DATETIME DATETIME,
    YEAR NUMBER,
    MONTH NUMBER,
    DAY NUMBER,
    DAY_OF_WEEK STRING,
    IS_WEEKEND BOOLEAN,
  	TRIP_DISTANCE FLOAT,
    TRIP_DURATION FLOAT,
    PU_LOCATIONID NUMBER,
	DO_LOCATIONID NUMBER,
    FARE_AMOUNT FLOAT,
    TIP_AMOUNT FLOAT,
    TOTAL_AMOUNT FLOAT,
    DRIVER_PAY FLOAT,
    DISPATCHING_BASE_NUM STRING
);

-- Create Statement for Outlier HVFHV data (OUTLIER_HVFHV)
CREATE OR REPLACE TRANSIENT TABLE CAPSTONE_DE.GROUP_1.OUTLIER_HVFHV (
    LICENSE_NUM STRING,
    PU_DATETIME DATETIME,
    DO_DATETIME DATETIME,
    REQUEST_DATETIME DATETIME,
    YEAR NUMBER,
    MONTH NUMBER,
    DAY NUMBER,
    DAY_OF_WEEK STRING,
    IS_WEEKEND BOOLEAN,
  	TRIP_DISTANCE FLOAT,
    TRIP_DURATION FLOAT,
    PU_LOCATIONID NUMBER,
	DO_LOCATIONID NUMBER,
    FARE_AMOUNT FLOAT,
    TIP_AMOUNT FLOAT,
    TOTAL_AMOUNT FLOAT,
    DRIVER_PAY FLOAT,
    DISPATCHING_BASE_NUM STRING
);

-- Create Statement for Taxi data (TAXI_TBL)
CREATE OR REPLACE TRANSIENT TABLE CAPSTONE_DE.GROUP_1.TAXI_TBL (
    VENDOR_ID NUMBER,
    PU_DATETIME DATETIME,
    DO_DATETIME DATETIME,
    YEAR NUMBER,
    MONTH NUMBER,
    DAY NUMBER,
    DAY_OF_WEEK STRING,
    IS_WEEKEND BOOLEAN,
    TRIP_DISTANCE FLOAT,
    TRIP_DURATION FLOAT,
    PU_LOCATIONID NUMBER,
    DO_LOCATIONID NUMBER,
    FARE_AMOUNT FLOAT,
    TIP_AMOUNT FLOAT,
    TOTAL_AMOUNT FLOAT,
    TRIP_TYPE NUMBER,
    TAXI_TYPE STRING
);

-- Create Statement for Outlier Taxi data (OUTLIER_TAXI)
CREATE OR REPLACE TRANSIENT TABLE CAPSTONE_DE.GROUP_1.OUTLIER_TAXI (
    VENDOR_ID NUMBER,
    PU_DATETIME DATETIME,
    DO_DATETIME DATETIME,
    YEAR NUMBER,
    MONTH NUMBER,
    DAY NUMBER,
    DAY_OF_WEEK STRING,
    IS_WEEKEND BOOLEAN,
    TRIP_DISTANCE FLOAT,
    TRIP_DURATION FLOAT,
    PU_LOCATIONID NUMBER,
    DO_LOCATIONID NUMBER,
    FARE_AMOUNT FLOAT,
    TIP_AMOUNT FLOAT,
    TOTAL_AMOUNT FLOAT,
    TRIP_TYPE NUMBER,
    TAXI_TYPE STRING
);

-- Create Statement for License Number data (LICENSE_TBL)
CREATE OR REPLACE TRANSIENT TABLE CAPSTONE_DE.GROUP_1.LICENSE_TBL (
    LICENSE_NUM STRING,
    COMPANY_NAME STRING
);

-- Create Statement for Taxi Zone data (TAXI_ZONE_TBL)
CREATE OR REPLACE TRANSIENT TABLE CAPSTONE_DE.GROUP_1.TAXI_ZONE_TBL (
    LOCATION_ID NUMBER,
    BOROUGH STRING,
    ZONE STRING,
    SERVICE_ZONE STRING
);

-- Create Statement for Landmarks data (LANDMARKS_TBL)
CREATE OR REPLACE TRANSIENT TABLE CAPSTONE_DE.GROUP_1.LANDMARKS_TBL (
    LANDMARK_NAME STRING,
    LANDMARK_ALTERNATE_NAME STRING,
    BUILDTYPE STRING,
    USE_ORIG STRING,
    USE_SECOND STRING,
    USE_TERTIA STRING,
    BOROUGH STRING,
    NEIGHBORHOOD STRING,
    ADDRESS STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    GEOMETRY STRING,
    FID STRING,
    OBJECTID STRING,
    BLOCK STRING,
    LOT STRING,
    BBL_CODE STRING,
    SHAPE_LENG FLOAT,
    SHAPE_AREA FLOAT,
    URL_IMAGE STRING,
    CATEGORY STRING
);

-- Insert Statements
-- Inserting into Taxi Table from partitioned transformed taxi data
INSERT INTO CAPSTONE_DE.GROUP_1.TAXI_TBL 
(VENDOR_ID, PU_DATETIME, DO_DATETIME, YEAR, MONTH, DAY, DAY_OF_WEEK, IS_WEEKEND, 
TRIP_DISTANCE, TRIP_DURATION, PU_LOCATIONID, DO_LOCATIONID, FARE_AMOUNT, TIP_AMOUNT, TOTAL_AMOUNT, TRIP_TYPE, TAXI_TYPE)
SELECT
    $1:VendorID::NUMBER AS VENDOR_ID,
    $1:tpep_pickup_datetime::DATETIME AS PU_DATETIME,
    $1:tpep_dropoff_datetime::DATETIME AS DO_DATETIME,
    REGEXP_SUBSTR(METADATA$FILENAME, 'Year=(\\d+)', 1, 1, 'e')::NUMBER AS YEAR,
    REGEXP_SUBSTR(METADATA$FILENAME, 'Month=(\\d+)', 1, 1, 'e')::NUMBER AS MONTH,
    REGEXP_SUBSTR(METADATA$FILENAME, 'Day=(\\d+)', 1, 1, 'e')::NUMBER AS DAY,
    $1:Day_Of_Week_Name::STRING AS DAY_OF_WEEK,
    $1:Is_Weekend::BOOLEAN AS IS_WEEKEND,
    $1:trip_distance::FLOAT AS TRIP_DISTANCE,
    $1:trip_duration::FLOAT AS TRIP_DURATION,
    $1:PULocationID::NUMBER AS PU_LOCATIONID,
    $1:DOLocationID::NUMBER AS DO_LOCATIONID,
    $1:fare_amount::FLOAT AS FARE_AMOUNT,
    $1:tip_amount::FLOAT AS TIP_AMOUNT,
    $1:total_amount::FLOAT AS TOTAL_AMOUNT,
    $1:trip_type::NUMBER AS TRIP_TYPE,
    $1:Taxi_Type::STRING AS TAXI_TYPE
FROM @CAPSTONE_DE.GROUP_1.TRANSFORMED_STAGE/taxi_transformed/ (FILE_FORMAT => 'group1_parquet_format', PATTERN => '.*parquet.*');

-- Inserting into High Volume Table from partitioned transformed hvfhv data
INSERT INTO CAPSTONE_DE.GROUP_1.HIGH_VOLUME_TBL (LICENSE_NUM, PU_DATETIME, DO_DATETIME, REQUEST_DATETIME, YEAR, MONTH, DAY, DAY_OF_WEEK, IS_WEEKEND, 
TRIP_DISTANCE, TRIP_DURATION, PU_LOCATIONID, DO_LOCATIONID, FARE_AMOUNT, TIP_AMOUNT, TOTAL_AMOUNT, DRIVER_PAY, DISPATCHING_BASE_NUM)
SELECT
    $1:hvfhs_license_num::STRING AS LICENSE_NUM,
    $1:tpep_pickup_datetime::DATETIME AS PU_DATETIME,
    $1:tpep_dropoff_datetime::DATETIME AS DO_DATETIME,
    $1:request_datetime::DATETIME AS REQUEST_DATETIME,
    REGEXP_SUBSTR(METADATA$FILENAME, 'Year=(\\d+)', 1, 1, 'e')::NUMBER AS YEAR,
    REGEXP_SUBSTR(METADATA$FILENAME, 'Month=(\\d+)', 1, 1, 'e')::NUMBER AS MONTH,
    REGEXP_SUBSTR(METADATA$FILENAME, 'Day=(\\d+)', 1, 1, 'e')::NUMBER AS DAY,
    $1:Day_Of_Week_Name::STRING AS DAY_OF_WEEK,
    $1:Is_Weekend::BOOLEAN AS IS_WEEKEND,
    $1:trip_distance::FLOAT AS TRIP_DISTANCE,
    $1:Trip_Duration::FLOAT AS TRIP_DURATION,
    $1:PULocationID::NUMBER AS PU_LOCATIONID,
    $1:DOLocationID::NUMBER AS DO_LOCATIONID,
    $1:fare_amount::FLOAT AS FARE_AMOUNT,
    $1:tip_amount::FLOAT AS TIP_AMOUNT,
    $1:total_amount::FLOAT AS TOTAL_AMOUNT,
    $1:driver_pay::FLOAT AS DRIVER_PAY,
    $1:dispatching_base_num::STRING AS DISPATCHING_BASE_NUM
FROM @CAPSTONE_DE.GROUP_1.TRANSFORMED_STAGE/hvfhv_transformed/ (FILE_FORMAT => 'group1_parquet_format', PATTERN => '.*parquet.*');

-- Inserting into Taxi Zone Table from zone lookup data
INSERT INTO CAPSTONE_DE.GROUP_1.TAXI_ZONE_TBL (LOCATION_ID, BOROUGH, ZONE, SERVICE_ZONE)
SELECT
    $1:LocationID::NUMBER AS LOCATION_ID,
    $1:Borough::STRING AS BOROUGH,
    $1:Zone::STRING AS ZONE,
    $1:service_zone::STRING as SERVICE_ZONE
FROM @CAPSTONE_DE.GROUP_1.TRANSFORMED_STAGE/zone_lookup/ (FILE_FORMAT => 'group1_parquet_format', PATTERN => '.*parquet.*');

-- Inserting into License Number Table from license data
COPY INTO CAPSTONE_DE.GROUP_1.LICENSE_TBL
FROM @CAPSTONE_DE.GROUP_1.TRANSFORMED_STAGE/license_table/
PATTERN = '.*parquet.*'
FILE_FORMAT = 'CAPSTONE_DE.GROUP_1.GROUP1_PARQUET_FORMAT'
ON_ERROR = CONTINUE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Inserting into Landmarks table from landmarks data
COPY INTO CAPSTONE_DE.GROUP_1.LANDMARKS_TBL
FROM @CAPSTONE_DE.GROUP_1.TRANSFORMED_STAGE/landmark_transformed/
PATTERN = '.*parquet.*'
FILE_FORMAT = 'CAPSTONE_DE.GROUP_1.GROUP1_PARQUET_FORMAT'
ON_ERROR = CONTINUE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
